### ISSUE TITLE
文档补充

### ISSUE THREAD

**Issue by jlkm2010** [TommyLemon/Android-ZBLibrary#1]
如果有个简单的文档，介绍下项目的架构思路，及各模块的功能，就更完善了

**Comment by TommyLemon** [comment]
项目结构看工程目录，目录下有package-info说明这个包的作用。
每个公共类都有详细的注释，包括作用和使用方法等。

比如
base包的package-info注释：
/**
 * 基础类所在包
 */
/**
 * @author Lemon
 * @use 通用使用方法：extends BaseXX
 */

BaseActivity的注释（里面的方法也几乎都有注释）
/**基础android.support.v4.app.FragmentActivity，通过继承可获取或使用 里面创建的 组件 和 方法
 * *onFling内控制左右滑动手势操作范围，可自定义
 * @author Lemon
 * @see ActivityPresenter#getActivity
 * @see #context
 * @see #view
 * @see #fragmentManager
 * @see #setContentView
 * @see #runUiThread
 * @see #runThread
 * @see #onDestroy
 * @use extends BaseActivity, 具体参考 .DemoActivity 和 .DemoFragmentActivity
 */
