### ISSUE TITLE
无法找到DemoHttpListActivity文件

### ISSUE THREAD

**Issue by beiguancyc** [TommyLemon/Android-ZBLibrary#10]
想学习下BaseHttpListActivity的具体用法，代码中说要参考DemoHttpListActivity，但是并无该文件

**Comment by TommyLemon** [comment]
抱歉，删掉了，可以参考zblibrary.demo.activity_fragment.UserListFragment，如果还不懂就加群我发你一份代码（项目主页readme文档最下方有群号）

**Comment by beiguancyc** [comment]
已经加群，希望通过，谢谢。
