### ISSUE TITLE
建议修改UIL为Glide或者Picasso

### ISSUE THREAD

**Issue by windhc** [TommyLemon/Android-ZBLibrary#12]
- UIL作者已经不再更新了
- 只是建议
- 谢谢你的项目

**Comment by TommyLemon** [comment]
这个值得考虑，ZBLibrary把对UIL的封装在ImageLoaderUtil.java，都是通过它去间接使用UIL，所以替换为其它图片加载库只需要改这个类

**Comment by TommyLemon** [comment]
@windhc 已支持Glide和RecyclerView
