### ISSUE TITLE
ScanActivity的画面被拉伸

### ISSUE THREAD

**Issue by cnyyk** [TommyLemon/Android-ZBLibrary#14]
ScanActivity的画面被拉伸。最后的版本也有这个问题。

**Comment by TommyLemon** [comment]
有解决过，改了某项配置后摄像画面倒是正常了，但导致识别率非常低，基本不可用，所以又改回去了。
或许要升级下版本，或改用其它二维码库才行。
ZBLibrary中QRCodeLibrary改自这个，改了取景框拉伸等问题，还新增支持自定义样式，但画面拉伸确实没有很好地解决。
https://github.com/xuyisheng/ZXingLib

**Comment by cnyyk** [comment]
其实可以不用zxinglib的。直接用原厂的就好了

`
dependencies {
    api fileTree(include: ['*.jar'], dir: 'libs')

    api 'com.google.zxing:core:3.3.1'

    testImplementation 'junit:junit:4.12'
}
`
识别率直逼支付宝和微信。

**Comment by TommyLemon** [comment]
已解决，ViewFinderView不能预览，我也打算换了
https://github.com/TommyLemon/Android-ZBLibrary/issues/16

**Comment by cnyyk** [comment]
Thanks for your great work
