### ISSUE TITLE
请问BaseHttpListActivity类的使用有没有范例

### ISSUE THREAD

**Issue by priscillatong** [TommyLemon/Android-ZBLibrary#15]
DEMO里没有找到，能否给个示例。新手刚学，还不太会运用，有个例子好借鉴，谢谢。

**Comment by TommyLemon** [comment]
@priscillatong  可以参考UserListFragment，除了继承不一样，Activity初始化函数onCreate和Fragment的onCreateView不一样，其它都一样

**Comment by TommyLemon** [comment]
@priscillatong 已新增DemoHttpListActivity,DemoHttpListFragment,DemoHttpRecyclerActivity,DemoHttpRecyclerFragment示例，欢迎使用新版ZBLibrary 16.6
https://github.com/TommyLemon/Android-ZBLibrary
