### ISSUE TITLE
非全屏下怎么设置zxing透明背景预览（应该是surfaceview）位置和大小，设置完扫码变形了

### ISSUE THREAD

**Issue by iamzj** [TommyLemon/Android-ZBLibrary#16]
![tim 20180102110554](https://user-images.githubusercontent.com/21978982/34473447-b16d8606-efad-11e7-9a4f-a2ec40d673a4.png)

**Comment by TommyLemon** [comment]
透明背景确实是用SurfaceView实现的，SurfaceView的宽高比决定了画面的宽高比。
所以要想不拉伸，需要设置它的width=height。ZBLibrary已更新，已经看不出拉伸了。

还有一个ViewfinderView用于显示中间的定位框，并在解析的时候有点阵提示。
ViewfinderView不能指定宽高，否则扫描读取成功率会很低。
