### ISSUE TITLE
该更新一些相应的组件了

### ISSUE THREAD

**Issue by WalkingBlue** [TommyLemon/Android-ZBLibrary#19]
作者应该更新一些东西了，至少AS要用3了吧，Gradle也得更新一下到4.4左右吧，还有相应用到的插件，如Glide，SmartRefreshLayout，OKHTTP等，还有编译平台什么的。目前用AS3编译要解决一堆问题，插件也不能更新，一更新，一堆错误

**Comment by TommyLemon** [comment]
请问是什么插件呢？

**Comment by coolmaye** [comment]
我的直接就行了啊，3.0一遍编译就通过了

**Comment by TommyLemon** [comment]
Gradle已升级至3.1.3，
OKHTTP已升级到最新版3.11.0，
感谢支持^_^
https://github.com/TommyLemon/Android-ZBLibrary/releases/tag/18.3

**Comment by TommyLemon** [comment]
@WalkingBlue 
使用Android Studio3.1.4(最新版) 和 gradle 4.4(最新版) 编译和测试通过
https://github.com/TommyLemon/Android-ZBLibrary/commit/04a3ba845ab28bc9f34777dbec4eaa5ea4b576ad
