### ISSUE TITLE
wanandroid进入后，底部几个tab来回点击，ftagment重叠了

### ISSUE THREAD

**Issue by chenxiaofei910714** [TommyLemon/Android-ZBLibrary#23]

**Comment by TommyLemon** [comment]
ZBLibraryDemoApp.apk下载链接是4月1日的，可能确实有这个问题。
今天已经更新了，试试重新下载APK
http://files.cnblogs.com/files/tommylemon/ZBLibraryDemoApp.apk
或 下载源码编译成APK
https://github.com/TommyLemon/Android-ZBLibrary/archive/master.zip

**Comment by TommyLemon** [comment]
如果还有问题，请提供详细的信息，包括：
1.当前使用的版本号
2.复现操作描述
3.使用代码
3.crash日志
4.图片或者视频
5.最好有demo

有详细的描述才能让作者快速地定位问题。

**Comment by TommyLemon** [comment]
既然你在邮件里说：
不好意思啊，我邮件发错了，不是你的项目，项目名称有点相似，我发错了邮箱！打扰了
那我就关掉这个issue了
