### ISSUE TITLE
关于mysql数据库的json数据处理问题

### ISSUE THREAD

**Issue by Domlaa** [TommyLemon/Android-ZBLibrary#27]
**问题描述**

您好，在参照您的数据库设计的时候，对于moment表的praiseUserIdList字段设计不是很理解。看到您里面的数据是一个数组，存放着点赞的用户id，在用户取消点赞时，怎么删除数组里面的用户的id呢，使用json_remove只能通过key或者数组下标删除，不能直接通过数组里的值删除。请问您是怎么处理的呢？

**Comment by TommyLemon** [comment]
目前不是通过 SQL 删的，而是在代码里 remove 掉
![image](https://user-images.githubusercontent.com/5738175/49698341-726f6200-fbfd-11e8-81ac-da110ecb5bde.png)

自动化 API 会调用这里的代码
https://github.com/TommyLemon/APIJSON/blob/4993aa48ec1ac832c9fc79c42214e7ae2c6cc4d0/APIJSON-Java-Server/APIJSONLibrary/src/main/java/zuo/biao/apijson/server/AbstractObjectParser.java

所以只需要这样请求就好
```js
{
    "Moment": {
        "id": 15,
        "praiseUserIdList-": [ //从praiseUserIdList里移除82001
            82001
        ]
    },
    "tag": "Moment"
}
```

**Comment by Domlaa** [comment]
好的，了解了。谢谢您
