### ISSUE TITLE
ZBLibrary更新

### ISSUE THREAD

**Issue by Batows** [TommyLemon/Android-ZBLibrary#3]
ZBLibrary更新时，是否能以Android Studio版本为主？

**Comment by TommyLemon** [comment]
@Batows eclipse开发比较快，所以先更新eclipse版，Android Studio版一般都会在随后一周内同步更新

**Comment by TommyLemon** [comment]
eclipse目录和as目录结构相近，把eclipse版的几个目录和文件（src,res,AndroidManifest）覆盖as对应的即可（as版QRCodeLibrary的theme不要改）。现在eclipse版部分新功能还在开发，等这几天开发完就会同步到as版
