### ISSUE TITLE
三星s8界面适配问题（沉浸式布局无效）

### ISSUE THREAD

**Issue by luoyongVM** [TommyLemon/Android-ZBLibrary#30]
**环境信息**
 机型与Android版本:  三星s8（SM-G950U）
  使用ZBLibrary版本:   19.2

**问题描述**
没有沉浸式效果，界面上下部有大面积空的地方
![qq 20190114110535](https://user-images.githubusercontent.com/45145447/51095077-121ba380-17ed-11e9-8163-bdf7dad6aac1.jpg)

**Comment by TommyLemon** [comment]
感谢贡献
https://github.com/TommyLemon/Android-ZBLibrary/pull/31
