### ISSUE TITLE
mac 导入 Android-ZBLibrary-master 报错

### ISSUE THREAD

**Issue by RPeast** [TommyLemon/Android-ZBLibrary#34]
![image](https://user-images.githubusercontent.com/38761029/53774316-ebdece00-3f28-11e9-8bd1-3959ab9c565f.png)

**Comment by RPeast** [comment]
按照使用教程走了一遍还是这个错误，新建项目导入ZBLibrary则不会报错

**Comment by beiguancyc** [comment]
这两个库可以直接从本地删掉从gradle引入

**Comment by RPeast** [comment]
> 这两个库可以直接从本地删掉从gradle引入

解决了 ，感谢
