### ISSUE TITLE
为什么不添加xutils这样的注解框架？

### ISSUE THREAD

**Issue by anybus** [TommyLemon/Android-ZBLibrary#4]
我是初学者 O(∩_∩)O~

**Comment by TommyLemon** [comment]
@anybus 
1.注解会导致编译和运行至少一方性能下降；
2.注解存在一些兼容性问题，混淆加密后可能失效；
3.代码迁移问题：如果公司不允许用注解框架，那么以前很多注解代码都废了；如果是非注解框架，即便不允许依赖，复制代码过去也能用。

**Comment by anybus** [comment]
3q !代码很不错！支持！
