### ISSUE TITLE
对话框能否锁定？不要点击旁边就自动消失了对话框。

### ISSUE THREAD

**Issue by tianxiaoyunyou** [TommyLemon/Android-ZBLibrary#44]
**具体说下**
对话框能否锁定？不要点击旁边就自动消失了对话框。

**为什么**
比如有个选项，希望能只能点击确定或者取消，以便根据用户的选择处理不同逻辑。结果点击旁边的遮罩层，对话框就消失了，结果事件都没有触发。

**Comment by TommyLemon** [comment]
dialog.setCanceledOnTouchOutside(false)

**Comment by tianxiaoyunyou** [comment]
谢谢老师。
