### ISSUE TITLE
安装之后打开吓到了

### ISSUE THREAD

**Issue by docwei2050** [TommyLemon/Android-ZBLibrary#48]
ui太拿不出手了，哎，我是找zxing库，找到你了，伤心

**Comment by TommyLemon** [comment]
UI 的美观程度不是开发自认为好看就行，符合设计图的才是对的。 不同的项目风格也不同，不可能一个 Demo 就能满足全部需求，自己调吧。 ZBLibrary 主要是对列表、网格、弹窗等常用组件的封装， 提供 BaseActivity，BaseListActivity, BaseHttpListActivity, BaseFragment，BaseListFragment, BaseHttpListFragment BaseAdapter, BaseView 等， 方便快速开发。
