### ISSUE TITLE
非常好的库

### ISSUE THREAD

**Issue by beiguancyc** [TommyLemon/Android-ZBLibrary#7]
非常感谢您的这个库，如果是想快速搭架子做项目的话，此库是不二选择。说明文档建议更新一下，因为没有一个清晰的文档，我尝试在httphead加了一对键值，没有成功，也没仔细追踪代码，但是查找了关键字符是支持的。

**Comment by TommyLemon** [comment]
@beiguancyc 文档在代码里，永远保持与代码同步，不用上网或打开文档。
项目结构看工程目录，目录下有package-info说明这个包的作用。
每个公共类都有详细的注释，包括作用和使用方法等。

比如
zuo.biao.library.base包的package-info注释：
/**
基础类所在包
/
/*
@author Lemon
@use 通用使用方法：extends BaseXX
*/
BaseActivity的注释（里面的方法也几乎都有注释）
/**基础android.support.v4.app.FragmentActivity，通过继承可获取或使用 里面创建的 组件 和 方法
*onFling内控制左右滑动手势操作范围，可自定义
@author Lemon
@see ActivityPresenter#getActivity
@see #context
@see #view
@see #fragmentManager
@see #setContentView
@see #runUiThread
@see #runThread
@see #onDestroy
@use extends BaseActivity, 具体参考 .DemoActivity 和 .DemoFragmentActivity
*/

**Comment by TommyLemon** [comment]
@beiguancyc 你在HttpHead加键值对的目的是？一般请求的键值对是直接在url后拼接的，例如
http://www.xxx.com/user/list?sex=1&city=杭州
HttpManager封装了OKHttp请求，里面有些TODO（包括测试用的JSON串）需要解决下才能用

package zuo.biao.library.manager;
/**HTTP请求管理类
 * @author Lemon
 * @use HttpManager.getInstance().get(...)或HttpManager.getInstance().post(...)  > 在回调方法onHttpRequestSuccess和onHttpRequestError处理HTTP请求结果
 * @must 解决getToken，getResponseCode，getResponseData中的TODO
 */
public class HttpManager {

**Comment by TommyLemon** [comment]
@beiguancyc 还有建议看看项目主页文档里的相关推荐，里面基本都是对ZBLibrary的功能作用及使用方法的说明

**Comment by beiguancyc** [comment]
@TommyLemon 感谢您的回复。最近正在阅读代码，获益良多。我接触的项目里httphead加键值对不外乎两个目的，一是传递参数，二是进行身份验证，通过head里的字段用固定算法对访问者身份进行校验。

**Comment by TommyLemon** [comment]
@beiguancyc 这样啊，我只在HttpHead里放过Cookie做校验。身份校验这种功能需要后端配合才行的，你要加的键值对必须要在服务器上能解析

**Comment by beiguancyc** [comment]
@TommyLemon 是的，解析肯定会在服务端。
