### ISSUE TITLE
报错：重复引用

### ISSUE THREAD

**Issue by beiguancyc** [TommyLemon/Android-ZBLibrary#8]
今天把框架推荐给了同事，系统为macOS10.12.
下载下来用AndroidStudio打开运行完全没问题。但是建立一个空白项目按照文章去添加引用后老是报错
![6fe8ea15-0dfb-4018-9e97-2732f3ef98ba](https://cloud.githubusercontent.com/assets/12932389/21854917/8bce7324-d857-11e6-88b6-b6856ff52da2.png)
随后不停clean和build，重启都无济于事。操作完全按照文章操作，并无添加其他库。

**Comment by beiguancyc** [comment]
或者这个错误
![171c1067-b6e1-4287-9d19-51732941aaf7](https://cloud.githubusercontent.com/assets/12932389/21855021/ec91cbd4-d857-11e6-9b4d-b35b4dd96abd.png)

**Comment by TommyLemon** [comment]
应该是新建的module依赖的v4包和ZBLibrary依赖的v4包版本不一样。
可以去掉新建项目的v4包依赖
或者 去掉ZBLibrary去掉自带的v4包依赖，然后依赖新建项目依赖的那个，最后去掉新建项目依赖的v4包。
如果还不行试试这个
https://my.oschina.net/tommylemon/blog/665242

**Comment by beiguancyc** [comment]
感谢回复，我是这么解决的，去掉v4的依赖包，然后把app和ZBbLibrary的gradle改成
provided fileTree(include: ['*.jar'], dir: 'libs')
可用。

**Comment by TommyLemon** [comment]
运行没问题那就是对的。这个方法我还不知道呢，刚试了下，运行所有功能都没发现问题。

**Comment by wq201** [comment]
解决重复引用的方法：
在项目的gradle配置中引用包时加入 exclude module: 'support-v4'，这样在引用包的时候就会排除v4包来引用了，就不会重复冲突。
![8b23394b-32c3-460f-821e-63fe2f440cc5](https://user-images.githubusercontent.com/27987027/39682191-185fb682-51e1-11e8-8725-299932a86755.png)
